version: 2.1

orbs:
  docker: circleci/docker@2.5.0

workflows:
  build-and-push:
    jobs:
      - docker/publish:
          image: ${DOCKER_IMAGE}
          tag: 'latest,${CIRCLE_SHA1}'
          dockerfile: Dockerfile
          path: .
          filters:
            branches:
              only:
                - main
                - develop
                - circleci-project-setup
